[package]
name = "castle-lending-aggregator"
version = "0.1.0"
description = "Created with Anchor"
edition = "2018"

[lib]
crate-type = ["cdylib", "lib"]
name = "castle_lending_aggregator"

[features]
no-entrypoint = []
no-idl = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.19.0"
anchor-spl = "0.19.0"
spl-math = {version = "0.1", features = ["no-entrypoint"]}
spl-token-lending = { git = "https://github.com/castle-finance/solana-program-library", version = "0.1.0", features = ["no-entrypoint"] }
port-anchor-adaptor = "0.2.8"