[programs.localnet]
castle_vault = "4tSMVfVbnwZcDwZB1M1j27dx9hdjL72VR9GM8AykpAvK"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/castle-vault.ts"

[mptest]
cmd = "yarn run ts-mocha -p ./tsconfig.json -t 1000000"
tests = "./tests/test_cases/"

[test.validator]
url = "m"

[[test.clone]]
# SOL/USD pyth product
address = "ALP8SdU9oARYVLgLR7LrqMNCYBnhtnQz1cj6bwgwQmgj"
[[test.clone]]
# SOL/USD pyth price
address = "H6ARHf6YXhGYeQfUzQNGk6rDNnLBQKrenN712K4AQJEG"
[[test.clone]]
# SOL/USD switchboard feed
address = "AdtRGGhmqvom3Jemp5YNrxd9q9unX36BZk1pujkkXijL"
[[test.clone]]
# Something to do with jet--serum?
address = "CjqQ9kx9STBLtSUdypHTjNJsLE4t6uQossjdSzq9jdmY"

[[test.genesis]]
address = "ALend7Ketfx5bxh6ghsCDXAoDrhvEmsXT3cynB6aPLgx"
program = "deps/solend_token_lending.so"
[[test.genesis]]
address = "pdQ2rQQU5zH2rDgZ7xH2azMBJegUzUyunJ5Jd637hC4"
program = "deps/port_finance_variable_rate_lending.so"
[[test.genesis]]
address = "stkarvwmSzv2BygN5e2LeTwimTczLWHCKPKGC2zVLiq"
program = "deps/port_finance_staking.so"
[[test.genesis]]
address = "JPv1rCqrhagNNmJVM5J1he7msQ5ybtvE1nNuHpDHMNU"
program = "deps/jet.so"
