name: Publish Package to npmjs
on:
  release:
    types: [created]
  # TODO delete
  # This is just for testing
  pull-request:
    branches: "*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"
          scope: "@castlefinance"
      - run: yarn
        working-directory: ./sdk
      - run: yarn publish
        working-directory: ./sdk
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
